name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-24.04
    services:
      postgres:
        image: postgres:15.3-alpine
        env:
          POSTGRES_DB: receipedb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    defaults:
      run:
        working-directory: 03-django-postgres
    env:
      DB_NAME: receipedb
      DB_USER: postgres
      DB_PASS: postgres
      DB_HOST: localhost
      SECRET_KEY: django-insecure-test-key-for-github-actions
      ALLOWED_HOSTS: "127.0.0.1,localhost"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: |
          docker build -t app .
          docker run --network=host --rm app sh -c "cd /src && python manage.py wait_for_db && python manage.py test"
      - name: Linting
        run: docker run --rm app sh -c "cd /src && flake8"
      - name: Formatter
        run: |
          docker run --rm -v "$(pwd)/src:/src" app sh -c "cd /src && chmod -R 777 . && black ."
