name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: 03-django-postgres

    env:
      DB_HOST: localhost # Changed from 'db' to 'localhost'
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1"
      POSTGRES_DB: ${{ secrets.DB_NAME }}
      POSTGRES_USER: ${{ secrets.DB_USER }}
      POSTGRES_PASSWORD: ${{ secrets.DB_PASS }}

    services:
      postgres: # Changed from 'db' to 'postgres'
        image: postgres:15.3-alpine
        env:
          POSTGRES_DB: ${{ secrets.DB_NAME }}
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASS }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Test
        run: docker compose -f docker-compose.yml run -e DB_HOST=localhost --rm app sh -c "cd /src && python manage.py wait_for_db && python manage.py test"

      - name: Linting
        run: docker compose -f docker-compose.yml run --rm app sh -c "cd /src && flake8"

      - name: Formatter
        run: docker compose -f docker-compose.yml run --rm app sh -c "cd /src && black app"
