name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: 03_Django_Postgres

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
      - name: Linting
        run: docker compose run --rm app sh -c "flake8"
      - name: Formatter
        run: docker compose run --rm app sh -c "black app"
