name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: 03-django-postgres
    env:
      DB_NAME: receipedb
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      DJANGO_ALLOWED_HOSTS: "127.0.0.1,localhost"

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Start services
        run: docker compose -f docker-compose.yml up -d
      - name: Wait for services
        run: sleep 10
      - name: Test
        run: docker compose -f docker-compose.yml run --rm app sh -c "cd /src && python manage.py wait_for_db && python manage.py test"
      - name: Linting
        run: docker compose run --rm app sh -c "cd /src && flake8"
      - name: Formatter
        run: docker compose run --rm app sh -c "cd /src && black ."
      - name: Cleanup
        if: always()
        run: docker compose -f docker-compose.yml down -v
